config/routes.rb
PoliRun::Application.routes.draw do
  match '/about', to: 'pagine#about'
  match '/contatti', to: 'pagine#contatti'
  root to: 'pagine#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pagine_controller.rb
class PagineController < ApplicationController
  def home
  end

  def about
  end

  def contatti
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    titolo_base="PoliRun"
    if page_title.empty? then
      return titolo_base
    else
      return "#{titolo_base} | #{page_title}"
    end
  end

end

app/helpers/pagine_helper.rb
module PagineHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pagine/about.html.erb
<% provide :title, "About"%>

<h1>Pagine#about</h1>
<p>Find me in app/views/pagine/about.html.erb</p>

app/views/pagine/contatti.html.erb
<h1>Pagine#contact</h1>
<p>Find me in app/views/pagine/contact.html.erb</p>

app/views/pagine/home.html.erb
<% provide :title, "Home"%>
<h1>Home</h1>

<!--<a href="#">About</a> -->
<%= link_to "About", about_path %> <!-- equivalente della riga sopra in rails-->
<%= link_to "Contatti", contatti_path %>